In [1]:
def mirror(seq):
    print(seq)
    output = list(seq[::-1])
    print(output)
    output.extend(seq[:])
    print(output)
    output.extend(seq[::-1])
    print(output)
    return output

inputs = [
   ['a', 'b', 'c'],
   ['d', 'e', 'f'],
   ['g', 'h', 'i'],
]

a = mirror([mirror(sublist) for sublist in inputs])

['a', 'b', 'c']
['c', 'b', 'a']
['c', 'b', 'a', 'a', 'b', 'c']
['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a']
['d', 'e', 'f']
['f', 'e', 'd']
['f', 'e', 'd', 'd', 'e', 'f']
['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd']
['g', 'h', 'i']
['i', 'h', 'g']
['i', 'h', 'g', 'g', 'h', 'i']
['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g']
[['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a'], ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'], ['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g']]
[['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'], ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'], ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a']]
[['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'], ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'], ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a'], ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a'], ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'], ['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g']]
[['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'], ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'], ['c', 'b', 

In [2]:
a

[['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'],
 ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'],
 ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a'],
 ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a'],
 ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'],
 ['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'],
 ['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'],
 ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'],
 ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a']]

In [2]:
import numpy as np

In [4]:
a = np.array(a)

In [5]:
a

array([['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'],
       ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'],
       ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a'],
       ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a'],
       ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'],
       ['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'],
       ['i', 'h', 'g', 'g', 'h', 'i', 'i', 'h', 'g'],
       ['f', 'e', 'd', 'd', 'e', 'f', 'f', 'e', 'd'],
       ['c', 'b', 'a', 'a', 'b', 'c', 'c', 'b', 'a']], dtype='<U1')

Функция:

In [11]:
half = 2

In [7]:
lst = [1, 2, 3]
lst_rev = lst[::-1][-half:]
#lst_rev = lst[:-2:-1]
lst_rev

[1]

In [12]:
b = np.array([
   [1, 2, 3, 4],
   [5, 6, 7, 8],
   [9, 10, 11, 12],
])

In [19]:
b.shape

(3, 4)

In [13]:
for i in b:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [14]:
def mirror(seq):
    output = list(seq[::-1][-half:])
    print(output)
    output.extend(seq[:])
    print(output)
    output.extend(seq[-1:-(half + 1):-1])
    print(output)
    return output

b_mirrored = mirror([mirror(sublist) for sublist in b])

[2, 1]
[2, 1, 1, 2, 3, 4]
[2, 1, 1, 2, 3, 4, 4, 3]
[6, 5]
[6, 5, 5, 6, 7, 8]
[6, 5, 5, 6, 7, 8, 8, 7]
[10, 9]
[10, 9, 9, 10, 11, 12]
[10, 9, 9, 10, 11, 12, 12, 11]
[[6, 5, 5, 6, 7, 8, 8, 7], [2, 1, 1, 2, 3, 4, 4, 3]]
[[6, 5, 5, 6, 7, 8, 8, 7], [2, 1, 1, 2, 3, 4, 4, 3], [2, 1, 1, 2, 3, 4, 4, 3], [6, 5, 5, 6, 7, 8, 8, 7], [10, 9, 9, 10, 11, 12, 12, 11]]
[[6, 5, 5, 6, 7, 8, 8, 7], [2, 1, 1, 2, 3, 4, 4, 3], [2, 1, 1, 2, 3, 4, 4, 3], [6, 5, 5, 6, 7, 8, 8, 7], [10, 9, 9, 10, 11, 12, 12, 11], [10, 9, 9, 10, 11, 12, 12, 11], [6, 5, 5, 6, 7, 8, 8, 7]]


In [15]:
b_mirrored

[[6, 5, 5, 6, 7, 8, 8, 7],
 [2, 1, 1, 2, 3, 4, 4, 3],
 [2, 1, 1, 2, 3, 4, 4, 3],
 [6, 5, 5, 6, 7, 8, 8, 7],
 [10, 9, 9, 10, 11, 12, 12, 11],
 [10, 9, 9, 10, 11, 12, 12, 11],
 [6, 5, 5, 6, 7, 8, 8, 7]]

In [16]:
b_mirrored = np.array(b_mirrored)

In [17]:
b_mirrored

array([[ 6,  5,  5,  6,  7,  8,  8,  7],
       [ 2,  1,  1,  2,  3,  4,  4,  3],
       [ 2,  1,  1,  2,  3,  4,  4,  3],
       [ 6,  5,  5,  6,  7,  8,  8,  7],
       [10,  9,  9, 10, 11, 12, 12, 11],
       [10,  9,  9, 10, 11, 12, 12, 11],
       [ 6,  5,  5,  6,  7,  8,  8,  7]])

In [18]:
b_mirrored.shape

(7, 8)

In [15]:
def mirror(seq, half):
    output = list(seq[::-1][-half:])
    output.extend(seq[:])
    output.extend(seq[-1:-(half + 1):-1])
    return output

In [16]:
def mirroring_border(arr, half):
    arr_mirrored = mirror([mirror(sublist, half) for sublist in arr], half)
    arr_mirrored = np.array(arr_mirrored)
    return arr_mirrored

In [17]:
arr = np.array([
   [1, 2, 3],
   [4, 5, 6],
   [7, 8, 9],
])

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr_mirrored = mirroring_border(arr, half)

In [20]:
arr_mirrored

array([[1, 1, 2, 3, 3],
       [1, 1, 2, 3, 3],
       [4, 4, 5, 6, 6],
       [7, 7, 8, 9, 9],
       [7, 7, 8, 9, 9]])

In [21]:
arr_mirrored.shape

(5, 5)