In [1]:
import numpy as np

In [2]:
img = np.array([[0, -8, -3, -2], [1, 9, -8, 0], [9, -4, 5, -9], [6, -4, 6, 3]])

In [3]:
img

array([[ 0, -8, -3, -2],
       [ 1,  9, -8,  0],
       [ 9, -4,  5, -9],
       [ 6, -4,  6,  3]])

In [4]:
kernel = np.array([[4, -5, 4], [-6, -8, -2], [1, 5, 5]])

In [5]:
kernel

array([[ 4, -5,  4],
       [-6, -8, -2],
       [ 1,  5,  5]])

numpy.fliplr(a) - отражает массив по горизонтали - элементы каждой строки переставляются в обратном порядке слева направо

numpy.flipud(a) - отражает массив по вертикали - элементы каждого столбца переставляются в обратном порядке сверху вниз

In [6]:
kernel_mirror = np.flipud(np.fliplr(kernel))

In [7]:
kernel_mirror

array([[ 5,  5,  1],
       [-2, -8, -6],
       [ 4, -5,  4]])

In [8]:
conv = np.array( [ [(img[:-1, :-1] * kernel_mirror).sum(),  (img[:-1, 1:] * kernel_mirror).sum() ], 
                  [(img[1:, :-1] * kernel_mirror).sum(), (img[1:, 1:] * kernel_mirror).sum()] ] )

In [9]:
conv

array([[  7, -88],
       [ 94,  -7]])

In [10]:
conv.shape

(2, 2)